title: Rizwan Police # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Test Automation Engineer
  <br><br>
  <a href="mailto:rizwaniiit@gmail.com">rizwaniiit@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/rizwan-p/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/rizwanpolice/">Gihub</a> 
theme: jekyll-theme-minimal
